#!/bin/bash

build_netatalk(){
    BUILD_DEPS="\
        build-essential \
        libevent-dev \
        libssl-dev \
        libgcrypt-dev \
        libkrb5-dev \
        libpam0g-dev \
        libwrap0-dev \
        libdb-dev \
        libtdb-dev \
        libmariadbclient-dev \
        libavahi-client-dev \
        libacl1-dev \
        libldap2-dev \
        libcrack2-dev \
        systemtap-sdt-dev \
        libdbus-1-dev \
        libdbus-glib-1-dev \
        libglib2.0-dev \
        libio-socket-inet6-perl \
        libtracker-sparql-1.0-dev \
        libtracker-miner-1.0-dev \
        file \
        wget \
        ca-certificates"

    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ${BUILD_DEPS} \
        tracker \
        libevent-2.0 \
        avahi-daemon \
        libavahi-client3 \
        libevent-core-2.0 \
        libwrap0 \
        libtdb1 \
        libmariadbclient18 \
        libcrack2 \
        libdbus-glib-1-2 \
        libssl1.1 \
        libgssapi-krb5-2

    cd /tmp
    wget "http://downloads.sourceforge.net/project/netatalk/netatalk/${NETATALK_VERSION}/netatalk-${NETATALK_VERSION}.tar.gz" -O /tmp/netatalk.tgz
    tar xvzf /tmp/netatalk.tgz
    cd /tmp/netatalk-${NETATALK_VERSION}
    ./configure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --with-pkgconfdir=/etc/netatalk \
        --with-init-style=debian-systemd \
        --without-libevent \
        --without-tdb \
        --with-cracklib \
        --enable-krbV-uam \
        --with-pam-confdir=/etc/pam.d \
        --with-dbus-sysconf-dir=/etc/dbus-1/system.d \
        --with-tracker-pkgconfig-version=1.0
    make -j `getconf _NPROCESSORS_ONLN`
    make install
    mkdir -p /var/log/netatalk
    DEBIAN_FRONTEND=noninteractive apt-get purge -y ${BUILD_DEPS}
    apt-get autoremove -y --purge
    apt-get clean
    rm -rf /var/lib/apt/lists/*
    rm -rf /tmp/*
    rm -rf /usr/share/icons
    rm -rf /usr/share/poppler
    rm -rf /usr/share/mime
    rm -rf /usr/share/GeoIP

}

set -e
set -x
export DEBIAN_FRONTEND=noninteractive

build_netatalk

apt-get update 
apt-get install -y \
    vsftpd \
    supervisor \
    nginx \
    php-fpm \
    openssh-server \
    nslcd
apt-get clean
cp -L /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
mkdir -p /var/run/sshd \
    /var/run/vsftpd/empty \
    /run/php

apt-get clean
rm -rf /var/lib/apt/lists/*

echo "session required    pam_exec.so /opt/init_home.sh" >> /etc/pam.d/common-session
